In [26]:
# imports
from embeddings_loader import *
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import roc_auc_score
import numpy as np
import os
from utils import *

--ip=127.0.0.1


In [6]:
train_labels, dev_labels, _ = load_labels()

In [7]:
label_replacement = {
    'OFF': 0,
    'NOT': 1
}

In [8]:
# Replace labels with numbers
train_labels = [label_replacement[label] for label in train_labels]
dev_labels = [label_replacement[label] for label in dev_labels]
# test_labels = [label_replacement[label] for label in test_labels]

In [31]:
mlp_classifier = MLPClassifier(max_iter=1000, early_stopping=True)
gridsearch = GridSearchCV(mlp_classifier, param_grid = {
	'hidden_layer_sizes' : [(128,64),(256,64)],
	'activation' : ['tanh', 'relu'],
	'solver' : ['sgd', 'adam'],
	'alpha' : [0.0001, 0.05],
	'learning_rate' : ['constant', 'adaptive']
}, scoring = "f1_macro", n_jobs=os.cpu_count()//3, verbose=2)

### Glove Twitter 25

In [11]:
gt25_train, gt25_dev, gt25_test = load_glove_twitter_25()

In [12]:
# Set all NaN values to 0
gt25_train = np.nan_to_num(gt25_train)
gt25_dev = np.nan_to_num(gt25_dev)
gt25_test = np.nan_to_num(gt25_test)

In [17]:
gt25_train[0]

array([ 0.29942665,  0.48439665,  0.48938234, -0.18078533,  0.51910998,
       -0.37910032,  0.12097333,  0.52592667,  0.16172   ,  0.20927335,
       -0.25639666, -0.34945001, -3.06763339, -0.64085334,  0.13807667,
       -0.125936  , -0.06390333, -0.16285634, -0.70355   , -0.38941667,
       -0.14004723, -0.52737866,  0.04168967,  0.49415   , -0.97523665])

In [32]:
grid_results = gridsearch.fit(gt25_train, train_labels)
best_params = grid_results.best_params_
mlp_classifier = grid_results.best_estimator_

Fitting 5 folds for each of 32 candidates, totalling 160 fits


In [33]:
best_params

{'activation': 'relu',
 'alpha': 0.0001,
 'hidden_layer_sizes': (128, 64),
 'learning_rate': 'constant',
 'solver': 'adam'}

In [34]:
mlp_classifier = mlp_classifier.fit(gt25_train, train_labels)
save_model(mlp_classifier, "mlp_classifier_gt25.joblib")

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\coding\\NLP_assignments\\NLP_Project\\Models\\ModelDumps\\mlp_classifier_gt25.joblib'

In [35]:
train_preds = mlp_classifier.predict(gt25_train)
dev_preds = mlp_classifier.predict(gt25_dev)
test_preds = mlp_classifier.predict(gt25_test)

In [36]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.7513217522658611
Accuracy Dev:  0.7322507552870091
Accuracy Test:  0.7825581395348837
Weighted F1 Train:  0.7347687767105369
Weighted F1 Dev:  0.7138957714513441
Weighted F1 Test:  0.76814165868434
Macro F1 Train:  0.6856254345290748
Macro F1 Dev:  0.6693427246336177
Macro F1 Test:  0.6969953895517862
Micro F1 Train:  0.7513217522658611
Micro F1 Dev:  0.7322507552870091
Micro F1 Test:  0.7825581395348837
Weighted Recall Train:  0.7513217522658611
Weighted Recall Dev:  0.7322507552870091
Weighted Recall Test:  0.7825581395348837
Macro Recall Train:  0.6737897185045398
Macro Recall Dev:  0.6605434840874191
Macro Recall Test:  0.6806451612903226
Micro Recall Train:  0.7513217522658611
Micro Recall Dev:  0.7322507552870091
Micro Recall Test:  0.7825581395348837
Confusion Matrix Train: 
[[1558 1927]
 [ 707 6400]]
Confusion Matrix Dev: 
[[ 392  523]
 [ 186 1547]]
Confusion Matrix Test: 
[[108 132]
 [ 55 565]]


### FastText 300 

In [37]:
ft300_train, ft300_dev, ft300_test = load_fasttext_300()

In [38]:
# Set all NaN values to 0
ft300_train = np.nan_to_num(ft300_train)
ft300_dev = np.nan_to_num(ft300_dev)
ft300_test = np.nan_to_num(ft300_test)

In [39]:
grid_results = gridsearch.fit(ft300_train, train_labels)
best_params = grid_results.best_params_
mlp_classifier = grid_results.best_estimator_

Fitting 5 folds for each of 32 candidates, totalling 160 fits


In [40]:
best_params

{'activation': 'relu',
 'alpha': 0.0001,
 'hidden_layer_sizes': (128, 64),
 'learning_rate': 'adaptive',
 'solver': 'adam'}

In [ ]:
mlp_classifier = mlp_classifier.fit(ft300_train, train_labels)
save_model(mlp_classifier, "mlp_classifier_ft300.joblib")

In [41]:
train_preds = mlp_classifier.predict(ft300_train)
dev_preds = mlp_classifier.predict(ft300_dev)
test_preds = mlp_classifier.predict(ft300_test)

In [42]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.801642749244713
Accuracy Dev:  0.7828549848942599
Accuracy Test:  0.8093023255813954
Weighted F1 Train:  0.7945270805879971
Weighted F1 Dev:  0.7759645731203891
Weighted F1 Test:  0.8000817786864298
Macro F1 Train:  0.7606598639327745
Macro F1 Dev:  0.746142579305435
Macro F1 Test:  0.7416849816849818
Micro F1 Train:  0.801642749244713
Micro F1 Dev:  0.7828549848942599
Micro F1 Test:  0.8093023255813954
Weighted Recall Train:  0.801642749244713
Weighted Recall Dev:  0.7828549848942599
Weighted Recall Test:  0.8093023255813954
Macro Recall Train:  0.7475549092888192
Macro Recall Dev:  0.7355730452577577
Macro Recall Test:  0.7247311827956989
Micro Recall Train:  0.801642749244713
Micro Recall Dev:  0.7828549848942599
Micro Recall Test:  0.8093023255813954
Confusion Matrix Train: 
[[2054 1431]
 [ 670 6437]]
Confusion Matrix Dev: 
[[ 533  382]
 [ 193 1540]]
Confusion Matrix Test: 
[[128 112]
 [ 52 568]]


### Word2Vec 300

In [43]:
w2v300_train, w2v300_dev, w2v300_test = load_word2vec_300()

In [44]:
# Set all NaN values to 0
w2v300_train = np.nan_to_num(w2v300_train)
w2v300_dev = np.nan_to_num(w2v300_dev)
w2v300_test = np.nan_to_num(w2v300_test)

In [45]:
grid_results = gridsearch.fit(w2v300_train, train_labels)
best_params = grid_results.best_params_
mlp_classifier = grid_results.best_estimator_

Fitting 5 folds for each of 32 candidates, totalling 160 fits


In [46]:
best_params

{'activation': 'relu',
 'alpha': 0.05,
 'hidden_layer_sizes': (256, 64),
 'learning_rate': 'adaptive',
 'solver': 'adam'}

In [ ]:
mlp_classifier = mlp_classifier.fit(w2v300_train, train_labels)
save_model(mlp_classifier, "mlp_classifier_w2v300.joblib")

In [47]:
train_preds = mlp_classifier.predict(w2v300_train)
dev_preds = mlp_classifier.predict(w2v300_dev)
test_preds = mlp_classifier.predict(w2v300_test)

In [48]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.8077794561933535
Accuracy Dev:  0.7719033232628398
Accuracy Test:  0.8209302325581396
Weighted F1 Train:  0.7994949557390421
Weighted F1 Dev:  0.7626060385359856
Weighted F1 Test:  0.8108073491161603
Macro F1 Train:  0.7653967050055014
Macro F1 Dev:  0.7295400432900432
Macro F1 Test:  0.7542382945874528
Micro F1 Train:  0.8077794561933533
Micro F1 Dev:  0.7719033232628398
Micro F1 Test:  0.8209302325581396
Weighted Recall Train:  0.8077794561933535
Weighted Recall Dev:  0.7719033232628398
Weighted Recall Test:  0.8209302325581396
Macro Recall Train:  0.7501536565784053
Macro Recall Dev:  0.7181784643326743
Macro Recall Test:  0.7340725806451613
Micro Recall Train:  0.8077794561933535
Micro Recall Dev:  0.7719033232628398
Micro Recall Test:  0.8209302325581396
Confusion Matrix Train: 
[[2027 1458]
 [ 578 6529]]
Confusion Matrix Dev: 
[[ 498  417]
 [ 187 1546]]
Confusion Matrix Test: 
[[129 111]
 [ 43 577]]


### Sentence Transformer

In [49]:
train, dev, test = load_sent_trans()

In [57]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
mlp_classifier = grid_results.best_estimator_

Fitting 5 folds for each of 32 candidates, totalling 160 fits


In [58]:
best_params

{'activation': 'relu',
 'alpha': 0.05,
 'hidden_layer_sizes': (128, 64),
 'learning_rate': 'adaptive',
 'solver': 'adam'}

In [ ]:
mlp_classifier = mlp_classifier.fit(train, train_labels)
save_model(mlp_classifier, "mlp_classifier_better_no_pca.joblib")

In [59]:
train_preds = mlp_classifier.predict(train)
dev_preds = mlp_classifier.predict(dev)
test_preds = mlp_classifier.predict(test)

In [60]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.7874811178247734
Accuracy Dev:  0.7651057401812689
Accuracy Test:  0.7953488372093023
Weighted F1 Train:  0.7810464862819329
Weighted F1 Dev:  0.759491366477479
Weighted F1 Test:  0.7881634372156692
Macro F1 Train:  0.7458937932982703
Macro F1 Dev:  0.7288743152128109
Macro F1 Test:  0.7288057850943518
Micro F1 Train:  0.7874811178247734
Micro F1 Dev:  0.765105740181269
Micro F1 Test:  0.7953488372093023
Weighted Recall Train:  0.7874811178247734
Weighted Recall Dev:  0.7651057401812689
Weighted Recall Test:  0.7953488372093023
Macro Recall Train:  0.7351008432488914
Macro Recall Dev:  0.7209810209403447
Macro Recall Test:  0.7163306451612903
Micro Recall Train:  0.7874811178247734
Micro Recall Dev:  0.7651057401812689
Micro Recall Test:  0.7953488372093023
Confusion Matrix Train: 
[[2028 1457]
 [ 794 6313]]
Confusion Matrix Dev: 
[[ 529  386]
 [ 236 1497]]
Confusion Matrix Test: 
[[129 111]
 [ 65 555]]
