In [2]:
# imports
from embeddings_loader import *
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import roc_auc_score
import numpy as np
import os
from utils import *

--ip=127.0.0.1


In [3]:
train_labels, dev_labels, _ = load_labels()

In [4]:
label_replacement = {
    'OFF': 0,
    'NOT': 1
}

In [5]:
# Replace labels with numbers
train_labels = [label_replacement[label] for label in train_labels]
dev_labels = [label_replacement[label] for label in dev_labels]
# test_labels = [label_replacement[label] for label in test_labels]

In [55]:
rf_classifier = RandomForestClassifier()
gridsearch = GridSearchCV(rf_classifier, param_grid = {
	'n_estimators' : [200],
	'max_features' : ['sqrt'],
	'bootstrap' : [True, False],
	'max_depth' : [8,9]
}, scoring = "f1_macro", n_jobs=os.cpu_count()//3, verbose=2)

### Glove Twitter 25

In [53]:
gt25_train, gt25_dev, gt25_test = load_glove_twitter_25()

In [54]:
# Set all NaN values to 0
gt25_train = np.nan_to_num(gt25_train)
gt25_dev = np.nan_to_num(gt25_dev)
gt25_test = np.nan_to_num(gt25_test)

In [9]:
gt25_train[0]

array([ 0.29942665,  0.48439665,  0.48938234, -0.18078533,  0.51910998,
       -0.37910032,  0.12097333,  0.52592667,  0.16172   ,  0.20927335,
       -0.25639666, -0.34945001, -3.06763339, -0.64085334,  0.13807667,
       -0.125936  , -0.06390333, -0.16285634, -0.70355   , -0.38941667,
       -0.14004723, -0.52737866,  0.04168967,  0.49415   , -0.97523665])

In [56]:
grid_results = gridsearch.fit(gt25_train, train_labels)
best_params = grid_results.best_params_
rf_classifier = grid_results.best_estimator_

Fitting 5 folds for each of 4 candidates, totalling 20 fits


In [57]:
best_params

{'bootstrap': False,
 'max_depth': 9,
 'max_features': 'sqrt',
 'n_estimators': 200}

In [58]:
rf_classifier = rf_classifier.fit(gt25_train, train_labels)
# save_model(rf_classifier, "rf_classifier_gt25.joblib")

In [59]:
train_preds = rf_classifier.predict(gt25_train)
dev_preds = rf_classifier.predict(gt25_dev)
test_preds = rf_classifier.predict(gt25_test)

In [60]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.8263783987915407
Accuracy Dev:  0.7054380664652568
Accuracy Test:  0.7790697674418605
Weighted F1 Train:  0.8104145880242066
Weighted F1 Dev:  0.6659388000749386
Weighted F1 Test:  0.7539632080938363
Macro F1 Train:  0.7725984188945243
Macro F1 Dev:  0.6040414822448998
Macro F1 Test:  0.6702746769337562
Micro F1 Train:  0.8263783987915407
Micro F1 Dev:  0.7054380664652568
Micro F1 Test:  0.7790697674418605
Weighted Recall Train:  0.8263783987915407
Weighted Recall Dev:  0.7054380664652568
Weighted Recall Test:  0.7790697674418605
Macro Recall Train:  0.7474883715390428
Macro Recall Dev:  0.6070435991789089
Macro Recall Test:  0.6526881720430108
Micro Recall Train:  0.8263783987915407
Micro Recall Dev:  0.7054380664652568
Micro Recall Test:  0.7790697674418605
Confusion Matrix Train: 
[[1801 1684]
 [ 155 6952]]
Confusion Matrix Dev: 
[[ 264  651]
 [ 129 1604]]
Confusion Matrix Test: 
[[ 88 152]
 [ 38 582]]


### FastText 300 

In [61]:
ft300_train, ft300_dev, ft300_test = load_fasttext_300()

In [62]:
# Set all NaN values to 0
ft300_train = np.nan_to_num(ft300_train)
ft300_dev = np.nan_to_num(ft300_dev)
ft300_test = np.nan_to_num(ft300_test)

In [63]:
grid_results = gridsearch.fit(ft300_train, train_labels)
best_params = grid_results.best_params_
rf_classifier = grid_results.best_estimator_

Fitting 5 folds for each of 4 candidates, totalling 20 fits


In [64]:
best_params

{'bootstrap': False,
 'max_depth': 9,
 'max_features': 'sqrt',
 'n_estimators': 200}

In [65]:
rf_classifier = rf_classifier.fit(ft300_train, train_labels)
# save_model(rf_classifier, "rf_classifier_ft300.joblib")

In [66]:
train_preds = rf_classifier.predict(ft300_train)
dev_preds = rf_classifier.predict(ft300_dev)
test_preds = rf_classifier.predict(ft300_test)

In [67]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.8824584592145015
Accuracy Dev:  0.7145015105740181
Accuracy Test:  0.772093023255814
Weighted F1 Train:  0.8748900500072457
Weighted F1 Dev:  0.6612097432413704
Weighted F1 Test:  0.7213185066796693
Macro F1 Train:  0.8518734436691422
Macro F1 Dev:  0.5922340064089245
Macro F1 Test:  0.6104316313984339
Micro F1 Train:  0.8824584592145015
Micro F1 Dev:  0.7145015105740181
Micro F1 Test:  0.772093023255814
Weighted Recall Train:  0.8824584592145015
Weighted Recall Dev:  0.7145015105740181
Weighted Recall Test:  0.772093023255814
Macro Recall Train:  0.8233515403711136
Macro Recall Dev:  0.6028769719271361
Macro Recall Test:  0.6057123655913978
Micro Recall Train:  0.8824584592145015
Micro Recall Dev:  0.7145015105740181
Micro Recall Test:  0.772093023255814
Confusion Matrix Train: 
[[2267 1218]
 [  27 7080]]
Confusion Matrix Dev: 
[[ 221  694]
 [  62 1671]]
Confusion Matrix Test: 
[[ 55 185]
 [ 11 609]]


### Word2Vec 300

In [68]:
w2v300_train, w2v300_dev, w2v300_test = load_word2vec_300()

In [69]:
# Set all NaN values to 0
w2v300_train = np.nan_to_num(w2v300_train)
w2v300_dev = np.nan_to_num(w2v300_dev)
w2v300_test = np.nan_to_num(w2v300_test)

In [70]:
grid_results = gridsearch.fit(w2v300_train, train_labels)
best_params = grid_results.best_params_
rf_classifier = grid_results.best_estimator_

Fitting 5 folds for each of 4 candidates, totalling 20 fits


In [71]:
best_params

{'bootstrap': False,
 'max_depth': 9,
 'max_features': 'sqrt',
 'n_estimators': 200}

In [72]:
rf_classifier = rf_classifier.fit(w2v300_train, train_labels)
# save_model(rf_classifier, "rf_classifier_w2v300.joblib")

In [73]:
train_preds = rf_classifier.predict(w2v300_train)
dev_preds = rf_classifier.predict(w2v300_dev)
test_preds = rf_classifier.predict(w2v300_test)

In [74]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.9004909365558912
Accuracy Dev:  0.7280966767371602
Accuracy Test:  0.7837209302325582
Weighted F1 Train:  0.8954538261103318
Weighted F1 Dev:  0.6839800486767458
Weighted F1 Test:  0.7437381074017311
Macro F1 Train:  0.8771361413374238
Macro F1 Dev:  0.6221865525236312
Macro F1 Test:  0.6463440517881778
Micro F1 Train:  0.9004909365558913
Micro F1 Dev:  0.7280966767371602
Micro F1 Test:  0.7837209302325583
Weighted Recall Train:  0.9004909365558912
Weighted Recall Dev:  0.7280966767371602
Weighted Recall Test:  0.7837209302325582
Macro Recall Train:  0.8509009344556734
Macro Recall Dev:  0.6240966894642412
Macro Recall Test:  0.6316532258064516
Micro Recall Train:  0.9004909365558912
Micro Recall Dev:  0.7280966767371602
Micro Recall Test:  0.7837209302325582
Confusion Matrix Train: 
[[2460 1025]
 [  29 7078]]
Confusion Matrix Dev: 
[[ 263  652]
 [  68 1665]]
Confusion Matrix Test: 
[[ 69 171]
 [ 15 605]]


### Sentence Transformer

In [75]:
train, dev, test = load_sent_trans()

In [76]:
grid_results = gridsearch.fit(train, train_labels)
best_params = grid_results.best_params_
rf_classifier = grid_results.best_estimator_

Fitting 5 folds for each of 4 candidates, totalling 20 fits


In [77]:
best_params

{'bootstrap': False,
 'max_depth': 9,
 'max_features': 'sqrt',
 'n_estimators': 200}

In [78]:
rf_classifier = rf_classifier.fit(train, train_labels)
# save_model(rf_classifier, "rf_classifier_better_no_pca.joblib")

In [79]:
train_preds = rf_classifier.predict(train)
dev_preds = rf_classifier.predict(dev)
test_preds = rf_classifier.predict(test)

In [80]:
computeAllScores(train_preds, dev_preds, test_preds)

Accuracy Train:  0.936083836858006
Accuracy Dev:  0.6952416918429003
Accuracy Test:  0.7430232558139535
Weighted F1 Train:  0.9341414890906509
Weighted F1 Dev:  0.6179845208747244
Weighted F1 Test:  0.6544976392050083
Macro F1 Train:  0.9235622656119129
Macro F1 Dev:  0.532928846780555
Macro F1 Test:  0.5008915464588931
Micro F1 Train:  0.936083836858006
Micro F1 Dev:  0.6952416918429003
Micro F1 Test:  0.7430232558139535
Weighted Recall Train:  0.936083836858006
Weighted Recall Dev:  0.6952416918429003
Weighted Recall Test:  0.7430232558139535
Macro Recall Train:  0.9033081535592751
Macro Recall Dev:  0.5672701875202987
Macro Recall Test:  0.5408602150537635
Micro Recall Train:  0.936083836858006
Micro Recall Dev:  0.6952416918429003
Micro Recall Test:  0.7430232558139535
Confusion Matrix Train: 
[[2814  671]
 [   6 7101]]
Confusion Matrix Dev: 
[[ 140  775]
 [  32 1701]]
Confusion Matrix Test: 
[[ 20 220]
 [  1 619]]
